[project]
name = 'Stacks-Wars'
description = 'A GameFi project on the Stacks blockchain'
authors = ['flames.stx']
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.factory]
path = 'contracts/factory.clar'
clarity_version = 3
epoch = 3.0

[contracts.verifying-signatures]
path = 'contracts/verifying-signatures.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
