[project]
name = 'Stacks-Wars'
description = 'A GameFi project on the Stacks blockchain'
authors = ['SWE Hashiras']
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.pool]
path = 'contracts/pool.clar'
clarity_version = 3
epoch = 3.0

[contracts.pool-1]
path = 'contracts/pool-1.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
